name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "00 15 * * *"
  # Manual triggers with workflow_dispatch
  workflow_dispatch:
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 717582064f27a8657219218a4f7fde7d
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
